"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""

import math


def divisible_triangle_number(n):
    triangle_number = 0
    current_number = 0
    while True:
        divisor_count = 0
        current_number += 1
        triangle_number += current_number
        root_value = int(math.sqrt(triangle_number))
        for divisor in range(1, root_value + 1):
            if (triangle_number % divisor) == 0:
                divisor_count += 2

        if root_value**2 == triangle_number:
            divisor_count -= 1

        if divisor_count >= n:
            print triangle_number
            return


if __name__ == '__main__':
    divisible_triangle_number(500)
